[options]
; This is the password that allows database operations:
admin_passwd = Lockic$8
db_host = False
db_port = 5433
db_user = odoo
db_password = odoo
;dbfilter = demo
addons_path =
    /Users/antoniocanovaspedreno/PycharmProjects/enterprise18,
    addons,
    /Users/antoniocanovaspedreno/PycharmProjects/clientes/18,
    /Users/antoniocanovaspedreno/PycharmProjects/navima_odoo,
    /Users/antoniocanovaspedreno/PycharmProjects/18industry


default_productivity_apps = True
wkhtmltopdf = /usr/local/bin/wkhtmltopdf
