[options]
; This is the password that allows database operations:
admin_passwd = Lockic$8
db_host = False
db_port = 5432
db_user = odoo
db_password = Lockic$8
;dbfilter = demo
addons_path =
    /Users/acanovas/pycharmprojects/18enterprise,
    addons,
    /Users/acanovas/pycharmprojects/clientes/18,
    /Users/acanovas/pycharmprojects/navima_odoo,
    /Users/acanovas/pycharmprojects/18industry


default_productivity_apps = True
wkhtmltopdf = /usr/local/bin/wkhtmltopdf
