from . import res_company
from . import shoes_product_sku_item
from . import shoes_sku
from . import product_image
from . import product_template
from . import product_product
from . import project_task
from . import project_project
from . import shoes_sample
from . import res_partner
