from . import set_template
from . import set_template_line
from . import product_template
from . import product_product
from . import res_company
from . import product_attribute_value
from . import product_template_attribute_value
from . import sale_order
from . import sale_order_line
from . import purchase_order
from . import purchase_order_line
from . import account_move
from . import account_move_line
from . import product_material
from . import mrp_bom
from . import project_project
from . import sale_report
from . import account_invoice_report
from . import shoes_report
from . import res_users
from . import stock_picking
from . import stock_move
from . import stock_move_line
from . import stock_warehouse_orderpoint
from . import shoes_hs_code
from . import shoes_pair_weight
from . import product_template_attribute_line
from . import assortment_pair
from . import product_attribute_custom_value
from . import stock_lot
from . import shoes_shape